spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/concurrency?useUnicode=true&characterEncoding=utf-8&serverZoneId=UTC
    username: root
    password: 12345
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.r2dbc.core: debug
